apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: gcr.io/${PROJECT_ID}/web:latest
          imagePullPolicy: 
          ports:
            - containerPort: 5000
          env:
            - name: STORAGE_SVC
              value: "http://storage:5000"
          livenessProbe:
            httpGet:
              path: /phrase
              port: 5000
            periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: 
spec:
  selector:
    app: web
  ports:
    - protocol: 
      port: 80
      targetPort: 5000
  type: LoadBalancer